name: Run tests

on:
  pull_request:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/run-tests.yml'
  push:
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - '.github/workflows/run-tests.yml'

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      # https://stackoverflow.com/questions/57612428/cloning-private-github-repository-within-organisation-in-actions
      # - name: Setup access to the private repository
      #   run: eval `ssh-agent -s` && ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Copy .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Generate laravel key
        run: php artisan key:generate

      - name: Setup directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ':memory:'
        run: php artisan test
