name: Typescript linting

on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/ts-linting.yml'
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.github/workflows/ts-linting.yml'

jobs:
  vue-tsc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # To generate php code to typescript
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Make database.sqlite
        run: touch database/database.sqlite
      - name: Generate typescript files
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate:fresh --seed && php artisan typescript:transform

      # Checking typescript
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Vue-tsc checking
        run: npx vue-tsc --noEmit --skipLibCheck
